<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginJobeetCategory extends BaseJobeetCategory
{

    public function getLatestPost() {
        $jobs = $this->getActiveJobs(1);

        return $jobs[0];
    }

    public function getActiveJobsQuery()
    {
      $q = Doctrine_Query::create()
        ->from('JobeetJob j')
        ->where('j.category_id = ?', $this->getId());

      return Doctrine::getTable('JobeetJob')->addActiveJobsQuery($q);
    }
    
    public function countActiveJobs() {
       return $this->getActiveJobsQuery()->count();
    }

    /*public function getSlug() {
        return Jobeet::slugify($this->getName());
    }*/
    
    public function getActiveJobs($max = 10) {
       $q = $this->getActiveJobsQuery()
                ->limit($max);

        return $q->execute();

    }
}
