<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2023/05/13 18:56:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'duarte86',
  'name' => 'doctrine',
)),);
