<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2023/05/13 18:56:10
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
